### PR TITLE
Switch to docker for builds

### PR DESCRIPTION
**Pull request by mrkurt**

### CODE REVIEW

**Comment by smeijer** [comment]
Big fan of the commit messages! 😂

**Comment by smeijer** [comment]
I've allowed your actions to run, sorry for the outcome.

**Comment by smeijer** [comment]
From now on, the actions should run automatically.

**Comment by kentcdodds** [comment]
Looks like we kinda need this before this makes much of a significant improvement: https://github.com/docker/build-push-action/issues/417

**Comment by mrkurt** [comment]
This appears to be working pretty well now, the "Docker Build" step on the last run in my repo took <1 min and used cached layers.

**Comment by kentcdodds** [comment]
How fast will that deploy?

**Comment by mrkurt** [comment]
Probably ~2 minutes. The resulting image is 70% smaller so it'll be faster to pull, we do a rolling deploy and update each of your VMs one by one, so total deploy time is a function of `count * (image-pull-time + time-to-healthy)`.

**Comment by kentcdodds** [comment]
Thanks a million Kurt!

**Pull request merged**
