### PR TITLE
feat: render content/pages using prose classes

### PR DESCRIPTION
**Pull request by smeijer**
I've applied the same header/image/content logic to the content pages, as we do for blog articles. This results in pretty rendering for:

- /appearances
- /clubs
- /conduct
- /info
- /links
- /transparency

I think the pages would benefit immensely if we'd added some banner images to them.

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Awesome! 

By banner, you mean like in blog posts?

**Comment by smeijer** [comment]
> By banner, you mean like in blog posts?

Exactly.

**Comment by kentcdodds** [comment]
Alright, do you want to add support for banners for the relevant pages and I'll add a banner to the mdx 👍

**Comment by smeijer** [comment]
I already did. It should work when you add `bannerUrl` and `bannerAlt` to the frontmatter.

I only need to fix the aspect ratio, I'll do that as part of #69.

**Comment by kentcdodds** [comment]
Oh, fantastic 👍 Thanks :)

**Pull request merged**
